export const dataNames = ['aayla secura', 'adi gallia', 'admiral dodd rancit',
'admiral firmus piett', 'admiral gial ackbar', 'admiral ozzel',
'admiral raddus', 'admiral terrinald screed', 'admiral trench',
'admiral u.o. statura', 'agen kolar', 'agent kallus', 'aiolin andmorit astarte', 'aks moe', 'almec', 'alton kastle', 'amee', 'ap-5',
'armitage hux', 'artoo', 'arvel crynyd', 'asajj ventress', 'aurra sing', 'azi-3', 'bala-tik', 'barada', 
'bargwill tomder', 'baronpapanoida', 'barriss offee', 'baze malbus', 'bazine netal', 'bb-8',
'bb-9e', 'ben quadinaros', 'berch teller', 'beru lars', 'bib fortuna',
'biggs darklighter', 'black krrsantan', 'bo-katan kryze', 'boba fett',
'bobbajo', 'bodhi rook', 'borvo the hutt', 'boss nass', 'bossk',
'breha antilles-organa', 'bren derlin', 'brendol hux', 'bt-1', 'c-3po',
'c1-10p', 'cad bane', 'caluan ematt', 'captain gregor', 'captainphasma',
'captain quarsh panaka', 'captain rex', 'carlist rieekan',
'casca panzoro', 'cassian andor', 'cassio tagge', 'cham syndulla',
'che amanwe papanoida', 'chewbacca', 'chi eekway papanoida', 'chiefchirpa',
'chirrut îmwe', 'ciena ree', 'cin drallig', 'clegg holdfast',
'cliegg lars', 'coleman kcaj', 'coleman trebor', 'colonel kaplan',
'commander bly', 'commander cody (cc-2224)', 'commander fil (cc-3714)',
'commander fox', 'commander gree', 'commander jet', 'commanderwolffe', 
'conan antonio motti', 'conder kyl', 'constable zuvio',
'cordé', 'cpatain typho', 'crix madine', 'cut lawquane', 'dak ralter',
'dapp', 'darth bane', 'darth maul', 'darth tyranus', 'daultay dofine',
'del meeko', 'delian mors', 'dengar', 'depa billaba', 'derek klivian',
'dexter jettster', 'dineé ellberger', 'dj', 'doctor aphra', 'doctorevazan', 'dogma', 'dormé', 'dr. cylo', 'droidbait', 'droopy mccool',
'dryden vos', 'dud bolt', 'ebe e. endocott', 'echuu shen-jon', 'eethkoth',
'eighth brother', 'eirtaé', 'eli vanto', 'ellé', 'ello asty',
'embo', 'eneb ray', 'enfys nest', 'ev-9d9', 'evaan verlaine', 'evenpiell', 'ezra bridger', 'faro argyus', 'feral', 'fifth brother',
'finis valorum', 'finn', 'fives', 'fn-1824', 'fn-2003', 'fodesinbeedannodue',
'fulcrum', 'fx-7', 'ga-97', 'galen erso', 'gallius rax',
'garazeb &quot;zeb&quot; orrelios', 'gardulla the hutt', 'garrick versio',
'garven dreis', 'gavyn sykes', 'gideon hask', 'gizor dellso', 'gonkdroid',
'grand inquisitor', 'greeata jendowanian', 'greedo', 'greersonnel', 'grievous', 'grummgar', 'gungi', 'hammerhead', 'han solo',
'harter kalonia', 'has obbit', 'hera syndulla', 'hevy', 'hondoohnaka',
'huyang', 'iden versio', 'ig-88', 'ima-gun di',
'inquisitors', 'inspector thanoth', 'jabba', 'jacen syndulla', 'jandodonna',
'jango fett', 'janus greejatus', 'jar jar binks', 'jasemari', 
'jaxxon', 'jek tono porkins', 'jeremoch colton', 'jira',
'jobal naberrie', 'jocasta nu', 'joclad danva', 'joh yowza', 'jombarell',
'joph seastriker', 'jova tarkin', 'jubnuk', 'jyn erso', 'k-2so',
'kanan jarrus', 'karbin', 'karina the great', 'kes dameron',
'ketsu onyo', 'ki-adi-mundi', 'king katuunko', 'kit fisto', 'kitsterbanai',
'klaatu', 'klik-klak', 'korr sella', 'kylo ren', 'l3-37',
'lama su', 'lando calrissian', 'lanever villecham', 'leia organa',
'letta turmond', 'lieutenant kaydel ko connix', 'lieutenant thire',
'lobot', 'logray', 'lok durd', 'longo two-guns', 'lor san tekka',
'lorth needa', 'lott dod', 'luke skywalker', 'lumat', 'luminaraunduli', 'lux bonteri', 'lyn me', 'lyra erso', 'mace windu',
'malakili', 'mama the hutt', 'mars guo', 'mas amedda', 'mawhonic',
'max rebo', 'maximilian veers', 'maz kanata', 'me-8d9', 'meena tills',
'mercurial swift', 'mina bonteri', 'miraj scintel', 'mister bones',
'mod terrik', 'moden canady', 'mon mothma', 'moradmin bast', 'moraloeval', 
'morley', 'mother talzin', 'nahdar vebb', 'nahdonnis praji',
'nien nunb', 'niima the hutt', 'nines', 'norra wexley', 'nute gunray',
'nuvo vindi', 'obi-wan kenobi', 'odd ball', 'ody mandrell', 'omi',
'onaconda farr', 'oola', 'oom-9', 'oppo rancisis', 'orn free taa',
'oro dassyne', 'orrimarko', 'osi sobeck', 'owen lars', 'pablo-jill',
'padmé amidala', 'pagetti rook', 'paige tico', 'paploo', 'pettyofficer thanisson',
'pharl mcquarrie', 'plo koon', 'po nudo', 'poedameron',
'poggle the lesser', 'pong krell', 'pooja naberrie', 'pz-4co', 
'quarrie', 'quay tolsite', 'queen apailana', 'queen jamillia',
'queen neeyutnee', 'qui-gon jinn', 'quiggold', 'quinlan vos', 'r2-d2',
'r2-kt', 'r3-s6', 'r4-p17', 'r5-d4', 'ra-7', 'rabé', 'rako hardeen',
'ransolm casterfo', 'rappertunie', 'ratts tyerell', 'raymus antilles',
'ree-yees', 'reeve panzoro', 'rey', 'ric olié', 'riff tamson',
'riley', 'rinnriyin di', 'rio durant', 'rogue squadron', 'romba',
'roos tarpals', 'rose tico', 'rotta the hutt', 'rukh', 'rune haako',
'rush clovis', 'ruwee naberrie', 'ryoo naberrie', 'sabé', 'sabinewren',
'saché', 'saelt-marae', 'saesee tiin', 'salacious b. crumb',
'san hill', 'sana starros', 'sarco plank', 'sarkli', 'satine kryze',
'savage opress', 'sebulba', 'senator organa', 'sergeant kreel',
'seventh sister', 'shaak ti', 'shara bey', 'shmi skywalker', 'shumai',
'sidon ithano', 'sifo-dyas', 'sim aloo', 'siniir rath velus','sio bibble',
'sixth brother', 'slowen lo', 'sly moore',
'snaggletooth', 'snap wexley', 'snoke', 'sola naberrie', 'sora bulq',
'strono tuggs', 'sy snootles', 'tallissan lintra', 'tarfful', 'tasuleech',
'taun we', 'tc-14', 'tee watt kaa', 'teebo', 'teedo', 'teemtopagalies', 
'temiri blagg', 'tessek', 'tey how', 'thane kyrell', 'thebendu', 
'the smuggler', 'thrawn', 'tiaan jerjerrod', 'tion medon',
'tobias beckett', 'tulon voidgazer', 'tup', 'u9-c4', 'unkar plutt',
'val beckett', 'vanden willard', 'vice admiral amilyn holdo', 'voberdand',
'wac-47', 'wag too', 'wald', 'walrus man', 'warok', 'wattambor',
'watto', 'wedge antilles', 'wes janson', 'wicket w. warrick',
'wilhuff tarkin', 'wollivan', 'wuher', 'wullf yularen', 'xamuellennox',
'yaddle', 'yarael poof', 'yoda', 'zam wesell', 'zev senesca',
'ziro the hutt', 'zuckuss']

